### ISSUE TITLE
Support semantic versioning

### ISSUE THREAD

**Issue by andyone** [uber-common/cpustat#16]
Hi! We plan to add cpustat to our [public repo](https://github.com/essentialkaos/kaos-repo) for CentOS/RHEL. But currently cpustat doesn't have version info. I highly recommend to use [sematic versioning](http://semver.org/) and use github releases.

**Comment by mranney** [comment]
OK, I did a github release tagged at 1.0.0. Does that work for you?

**Comment by andyone** [comment]
Yes, thanks!
